### ISSUE TITLE
Split second issue when setting a note causing both successful and failure message to appear

### ISSUE THREAD

**Issue by ajax146** [effprime/BasementBot#470]
If a note is set at the right moment when a user is leaving the server, a different error occurs and both a successful and failure message appears.
![2022-01-09_21-42](https://user-images.githubusercontent.com/31014239/148713110-3e51e488-d635-4895-a2a1-e1b06b70f9e2.png)
![2022-01-09_21-42_1](https://user-images.githubusercontent.com/31014239/148713159-4ac6eb95-a93e-4b5c-a6bf-a352661995e6.png)

I believe the note was set correctly but the role assignment caused the error.

I don't think I can repeat this.

**Comment by effprime** [comment]
This is probably intended behavior since the bot was just notifying you of an exception that occurred even though it still succeeded in the database call (which it did confirm to you about). Besides wrapping the add_roles call in a try block, I'd have to look at more complex solutions to this. But again, one could argue it's intended behavior.

**Comment by ajax146** [comment]
I thought about it being intended as well. Something about it giving both a positive and negative response just seems off. Maybe something like a partially succeeded message would suit it better.

Like you said, it would probably be a complex solution, and this is highly unlikely to happen again, so really not all that important either.

**Comment by effprime** [comment]
I've gone ahead and moved the confirmation to *after* the roles are added. That way, you'll only see it when no exceptions are thrown. This *does* mean you'll see an error even when the note is added in that case, but the user can verify if the note was added with another `whois` command.
